server.port=8080

spring.application.name=devops-challenge

spring.datasource.url=jdbc:postgresql://localhost:5432/devops
spring.datasource.username=devops
spring.datasource.password=devops123

management.endpoints.web.exposure.include=health,info

management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true